// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Tokens is the predicate function for tokens builders.
type Tokens func(*sql.Selector)
