// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/tvastar/goat/tokens/ent/migrate"

	"github.com/tvastar/goat/tokens/ent/tokens"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Tokens is the client for interacting with the Tokens builders.
	Tokens *TokensClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Tokens = NewTokensClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Tokens: NewTokensClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config: cfg,
		Tokens: NewTokensClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Tokens.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Tokens.Use(hooks...)
}

// TokensClient is a client for the Tokens schema.
type TokensClient struct {
	config
}

// NewTokensClient returns a client for the Tokens from the given config.
func NewTokensClient(c config) *TokensClient {
	return &TokensClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tokens.Hooks(f(g(h())))`.
func (c *TokensClient) Use(hooks ...Hook) {
	c.hooks.Tokens = append(c.hooks.Tokens, hooks...)
}

// Create returns a create builder for Tokens.
func (c *TokensClient) Create() *TokensCreate {
	mutation := newTokensMutation(c.config, OpCreate)
	return &TokensCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Tokens.
func (c *TokensClient) Update() *TokensUpdate {
	mutation := newTokensMutation(c.config, OpUpdate)
	return &TokensUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TokensClient) UpdateOne(t *Tokens) *TokensUpdateOne {
	mutation := newTokensMutation(c.config, OpUpdateOne, withTokens(t))
	return &TokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TokensClient) UpdateOneID(id int) *TokensUpdateOne {
	mutation := newTokensMutation(c.config, OpUpdateOne, withTokensID(id))
	return &TokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tokens.
func (c *TokensClient) Delete() *TokensDelete {
	mutation := newTokensMutation(c.config, OpDelete)
	return &TokensDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TokensClient) DeleteOne(t *Tokens) *TokensDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TokensClient) DeleteOneID(id int) *TokensDeleteOne {
	builder := c.Delete().Where(tokens.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TokensDeleteOne{builder}
}

// Create returns a query builder for Tokens.
func (c *TokensClient) Query() *TokensQuery {
	return &TokensQuery{config: c.config}
}

// Get returns a Tokens entity by its id.
func (c *TokensClient) Get(ctx context.Context, id int) (*Tokens, error) {
	return c.Query().Where(tokens.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TokensClient) GetX(ctx context.Context, id int) *Tokens {
	t, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return t
}

// Hooks returns the client hooks.
func (c *TokensClient) Hooks() []Hook {
	return c.hooks.Tokens
}
