// Code generated by entc, DO NOT EDIT.

package tokens

const (
	// Label holds the string label denoting the tokens type in the database.
	Label = "tokens"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"

	// Table holds the table name of the tokens in the database.
	Table = "tokens"
)

// Columns holds all SQL columns for tokens fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldUser,
	FieldToken,
}
